### ISSUE TITLE
Question about anchors

### ISSUE THREAD

**Issue by gray311** [jmwang0117/HE-Drive#3]
Thanks for your great job. I have some questions about the paper:

1. Do you fine-tune Llama3.2V for VLM scoring?
2. How do you plot the anchors and where are the anchors from? (from your code, it seems that your anchors are from GT or predict  by sparsebev, I am not sure)
3. I noticed that you conducted an ablation study about the number of anchors, but how do you choose important anchors to be plotted in the image?

**Comment by jmwang0117** [comment]
**1. Fine-tuning Llama 3.2V:** Instead of directly fine-tuning Llama 3.2V for VLM scoring, we collect a VQA dataset and engage in multi-round dialogues with Llama 3.2V to create historical contexts for adjusting driving styles. This allows Llama 3.2V to adapt the weights of the rule-based scorer based on the input images and questions from new scenarios. By doing so, we maintain the interpretability of the scorer while leveraging Llama 3.2V to adjust driving styles according to the scene, thus avoiding the hallucination issues associated with directly using large models as scorers.

**2.Plotting anchors:** The anchors are generated by sparse perceptual predictions. 

**3.Selecting important anchors:** The rule-based trajectory scorer evaluates each generated trajectory, and Llama 3.2V determines whether the current driving style should be aggressive or conservative based on the current scene. It then adjusts the weights of the rule-based scorer accordingly. Finally, the trajectory with the lowest score (i.e., the minimum cost) is selected from the set of trajectories to control the vehicle.
